Default choises
rabingaire/github-init pull request #5
Opened 2017-10-30 08:05 UTC by Leefrost

Small changes, just forgot to push

2017-10-30 09:22 UTC, rabingaire commented
This all has been implemented please look at the master branch :) I have already merged your PR

2017-10-30 10:17 UTC, Leefrost commented
Yeap, I read it before. In the last commit, I moved out default choices to dedicated massive and reuse it in the dialog. I just forgot to push it and back to it today. I have resolved the conflict. Sorry for late changes

2017-10-30 14:22 UTC, rabingaire requested changes

2017-10-30 14:22 UTC, rabingaire commented on index.js
> +const lang = require('../lang/default')
It should be ./lang/default not ../lang/default

2017-10-31 03:53 UTC, rabingaire commented
And there has been a new update on code please pull it and push again sorry for trouble :)

2018-04-22 14:51 UTC, closed without merging

2018-04-22 14:51 UTC, rabingaire commented
There was no activity for a long time so I closed this PR